# Generated by Django 2.1.7 on 2019-07-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_offers_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='city',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='operators',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='periods',
            old_name='period',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='types',
            old_name='types',
            new_name='value',
        ),
    ]
