# Generated by Django 2.1.7 on 2019-07-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190713_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periods',
            name='value',
            field=models.CharField(max_length=30),
        ),
    ]
