# Generated by Django 2.1.7 on 2019-07-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('types', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.AddField(
            model_name='offers',
            name='types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Types'),
            preserve_default=False,
        ),
    ]
