# Generated by Django 2.1.7 on 2019-07-11 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190711_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('types', models.CharField(default='1', max_length=50)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.AddField(
            model_name='offers',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.Cities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='period',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.Periods'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='price',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='speed',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='types',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.Types'),
            preserve_default=False,
        ),
    ]
