# Generated by Django 2.1.7 on 2019-07-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contacts_offer_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('operator', models.CharField(max_length=30)),
                ('period', models.IntegerField()),
                ('price', models.FloatField()),
                ('speed', models.IntegerField()),
                ('types', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='types',
            name='types',
            field=models.CharField(max_length=50),
        ),
    ]
