# Generated by Django 2.1.7 on 2019-08-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190718_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'parameters',
            },
        ),
    ]
