# Generated by Django 2.1.7 on 2019-11-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190925_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='value_pl',
        ),
        migrations.AddField(
            model_name='cities',
            name='count',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cities',
            name='name',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
    ]
