# Generated by Django 2.1.7 on 2019-11-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191125_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='name',
            new_name='value',
        ),
    ]
