# Generated by Django 2.1.7 on 2019-07-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190711_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='types',
        ),
    ]
