# Generated by Django 2.1.7 on 2019-07-11 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=30)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Operators')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Offer_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_time', models.IntegerField()),
                ('delivery_cost', models.IntegerField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Offers')),
            ],
            options={
                'db_table': 'offer_details',
            },
        ),
    ]
