# Generated by Django 2.1.7 on 2019-08-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='name',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
    ]
